version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: log430-app-renamed
    depends_on:
      - db
    watch: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: magasin
